runs:
  using: "composite"

  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install
      shell: bash

    - name: Install the project
      run: uv sync --all-extras --dev
      shell: bash
