name: Check *.py

on:
  pull_request:

jobs:
  Check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Set $GITHUB_PATH
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install packages
        run: poetry install

      - name: Lint
        run: make pysen-lint

      - name: Test
        run: make pytest
