name: CI

on:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install the project
        uses: ./.github/actions

      - name: Run tests
        run: make pytest

  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install the project
        uses: ./.github/actions

      - name: Run linter
        run: make ruff-check

  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install the project
        uses: ./.github/actions

      - name: Run type checker
        run: make mypy
